/* Alerta Errores */
"use strict"

// Ver y Ocultar info de Cartelera
$(document).ready(function(){
    $(".showone").click(function(){
        $(".div1").slideDown(500);
    });
    $(".hideone").click(function(){
        $(".div1").slideUp(500);
    });
    $(".showtwo").click(function(){
        $(".div2").slideDown(500);
    });
    $(".hidetwo").click(function(){
        $(".div2").slideUp(500);
    });
    $(".showthree").click(function(){
        $(".div3").slideDown(500);
    });
    $(".hidethree").click(function(){
        $(".div3").slideUp(500);
    });
    $(".showfour").click(function(){
        $(".div4").slideDown(500);
    });
    $(".hidefour").click(function(){
        $(".div4").slideUp(500);
    });
    $(".showfive").click(function(){
        $(".div5").slideDown(500);
    });
    $(".hidefive").click(function(){
        $(".div5").slideUp(500);
    });
    $(".showsix").click(function(){
        $(".div6").slideDown(500);
    });
    $(".hidesix").click(function(){
        $(".div6").slideUp(500);
    });
    $(".showseven").click(function(){
        $(".div7").slideDown(500);
    });
    $(".hideseven").click(function(){
        $(".div7").slideUp(500);
    });
    $(".showeight").click(function(){
        $(".div8").slideDown(500);
    });
    $(".hideeight").click(function(){
        $(".div8").slideUp(500);
    });
    $(".shownine").click(function(){
        $(".div9").slideDown(500);
    });
    $(".hidenine").click(function(){
        $(".div9").slideUp(500);
    });
    $(".showten").click(function(){
        $(".div10").slideDown(500);
    });
    $(".hideten").click(function(){
        $(".div10").slideUp(500);
    });
});

// Mostrar y Ocultar Películas de cada Género
$(document).ready(function(){
    $(".ver1").click(function(){
        $(".hide1").slideDown(1000);
    });
    $(".esconder1").click(function(){
        $(".hide1").slideUp(1000);
    });
    $(".ver2").click(function(){
        $(".hide2").slideDown(1000);
    });
    $(".esconder2").click(function(){
        $(".hide2").slideUp(1000);
    });
    $(".ver3").click(function(){
        $(".hide3").slideDown(1000);
    });
    $(".esconder3").click(function(){
        $(".hide3").slideUp(1000);
    });
    $(".ver4").click(function(){
        $(".hide4").slideDown(1000);
    });
    $(".esconder4").click(function(){
        $(".hide4").slideUp(1000);
    });
    $(".ver5").click(function(){
        $(".hide5").slideDown(1000);
    });
    $(".esconder5").click(function(){
        $(".hide5").slideUp(1000);
    });
    $(".ver6").click(function(){
        $(".hide6").slideDown(1000);
    });
    $(".esconder6").click(function(){
        $(".hide6").slideUp(1000);
    });
    $(".ver7").click(function(){
        $(".hide7").slideDown(1000);
    });
    $(".esconder7").click(function(){
        $(".hide7").slideUp(1000);
    });
    $(".ver8").click(function(){
        $(".hide8").slideDown(1000);
    });
    $(".esconder8").click(function(){
        $(".hide8").slideUp(1000);
    });

});
